DATALOADER:
  NUM_WORKERS: 0
DEVICE: "cuda"
SEED: 40244023
MODEL:
  BACKBONE: "resnet18"
  NUM_PROPOSALS: 128
  FPN:
    OUT_CHANNELS: 256
  ROI_HEADS:
    IN_FEATURES: ['p2', 'p3', 'p4', 'p5']
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    USE_LEVEL_POOLER: True
    POOLER_SAMPLING_RATIO: 2
    POOLER_TYPE: "ROIAlignV2"
  SparseRCNN:
    NUM_CLASSES: 80
    NUM_CLS: 1
    HIDDEN_DIM: 256
    DIM_FEEDFORWARD: 2048
    NHEADS: 8
    DROPOUT: 0.0
    ACTIVATION: "relu"
    NUM_HEADS: 6
    DEEP_SUPERVISION: True
    USE_FOCAL: True
    PRIOR_PROB: 0.01
    DIM_DYNAMIC: 64
    NUM_DYNAMIC: 2
    NUM_REG: 3
  LOSS:
    FOCAL_LOSS_GAMMA: 2.0
    FOCAL_LOSS_ALPHA: 0.25

    CLASS_WEIGHT: 2.0
    GIOU_WEIGHT: 2.0
    L1_WEIGHT: 5.0
    NO_OBJECT_WEIGHT: 0.1

SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.000025
  STEPS: [210000, 250000]
  NUM_EPOCHS: 30
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  GAMMA: 0.1
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 1000
  WARMUP_METHOD: "linear"
  WEIGHT_DECAY: 0.0001
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 1.0  # keep same with BASE_LR.
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 1.0
    NORM_TYPE: 2.0