DATALOADER:
  NUM_WORKERS: 0

MODEL:
  BACKBONE: "resnet18"
  NUM_PROPOSALS: 128
  FPN:
    OUT_CHANNELS: 256
  ROI_HEADS:
    IN_FEATURES: ['p2', 'p3', 'p4', 'p5']
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    USE_LEVEL_POOLER: True
    POOLER_SAMPLING_RATIO: 2
    POOLER_TYPE: "ROIAlignV2"
  SparseRCNN:
    NUM_CLASSES: 80
    NUM_CLS: 1
    HIDDEN_DIM: 256
    DIM_FEEDFORWARD: 2048
    NHEADS: 8
    DROPOUT: 0.0
    ACTIVATION: "relu"
    NUM_HEADS: 6
    DEEP_SUPERVISION: True
    USE_FOCAL: True
    PRIOR_PROB: 0.01
    DIM_DYNAMIC: 64
    NUM_DYNAMIC: 2
    NUM_REG: 3
